Camera Tracking
FairportRobotics/potential-octo-eureka pull request #1
Opened 2023-01-21 19:38 UTC by Declipsonator

# Camera Tracking
## AprilTags.java
See all the AprilTags around the robot. Supports multiple cameras (takes the one with the highest ambiguity) and has a few functions to find the closest target/the target with the best ambiguity.
## RobotFieldPosition.java
Small class to see where the robot is in the game. Does not support multiple cameras (Just using what photonvision gives us) and uses WpiLib's AprilTags field layout

2023-01-28 18:02 UTC, tywilly commented on lib/build.gradle
> +    implementation "edu.wpi.first.apriltag:apriltag-java:2023.2.1"
Add a plus to the version to take the latest versions. Refer to the old versions for help

2023-01-28 18:07 UTC, tywilly commented on lib/src/main/java/com/fairportrobotics/frc/poe/CameraTracking/AprilTags.java
> +                        targets.remove(arTarget);
Concurrent array modification. Create a temp array for operations

2023-01-28 18:08 UTC, tywilly commented on lib/src/main/java/com/fairportrobotics/frc/poe/CameraTracking/AprilTags.java
> +            targets.addAll(camera.getLatestResult().getTargets());
?????

2023-01-28 18:12 UTC, tywilly commented on lib/src/main/java/com/fairportrobotics/frc/poe/CameraTracking/AprilTags.java
> +            if(closestTarget == null || calculateDistance(target.getBestCameraToTarget()) > calculateDistance(target.getBestCameraToTarget()) ) closestTarget = target;
Checking difference between same targets

2023-01-28 18:14 UTC, tywilly commented on lib/src/main/java/com/fairportrobotics/frc/poe/CameraTracking/AprilTags.java
> +        return false;
```suggestion
         // if a camera has targets, return true
         return cameras.stream().anyMatch((camera) -> camera.getLatestResult().hasTargets() == true);
```

2023-01-28 18:25 UTC, tywilly commented on lib/src/main/java/com/fairportrobotics/frc/poe/CameraTracking/AprilTags.java
> +        return Math.sqrt(t.getX()*t.getX() + t.getY()*t.getY() + t.getZ()*t.getZ());
Remove Z dimension

And

This only calculates the distance from the passed in object and itself.

Camera is at 0,0 so try this

```suggestion
        return Math.sqrt(Math.pow(t.getX()-0,2) + Math.pow(t.getY()-0, 2));
```

Or

```suggestion
        return Math.sqrt(t.getX()*t.getX() + t.getY()*t.getY());
```

2023-01-28 18:29 UTC, tywilly commented on lib/src/main/java/com/fairportrobotics/frc/poe/CameraTracking/RobotFieldPosition.java
> +            layout = AprilTagFieldLayout.loadFromResource(AprilTagFields.k2022RapidReact.m_resourceFile);
2022??

2023-01-28 21:06 UTC, tywilly requested changes
Check posted comments for suggestions

2023-02-17 00:53 UTC, Declipsonator commented
# Changes
### Freeze and Unfreeze Method
When using AprilTags across multiple lines like this:
```
    if(aprilTags.hasTargets()) {
      SmartDashboard.putNumber("Closest AprilTag ID", aprilTags.getClosestTarget().getFiducialId());
      SmartDashboard.putString("Closest AprilTag Position", aprilTags.getClosestTarget().getBestCameraToTarget().toString());

      SmartDashboard.putNumber("Lowest AprilTag Ambiguity ID", aprilTags.getLowestAmbiguityTarget().getFiducialId());
      SmartDashboard.putNumber("Lowest AprilTag Ambiguity Ambiguity", aprilTags.getLowestAmbiguityTarget().getPoseAmbiguity());

    }
```

The targets inside AprilTags can change since they are not synchronized, causing crashes. By using the methods like this:
```
    aprilTags.freeze();
    
    if(aprilTags.hasTargets()) {
      SmartDashboard.putNumber("Closest AprilTag ID", aprilTags.getClosestTarget().getFiducialId());
      SmartDashboard.putString("Closest AprilTag Position", aprilTags.getClosestTarget().getBestCameraToTarget().toString());

      SmartDashboard.putNumber("Lowest AprilTag Ambiguity ID", aprilTags.getLowestAmbiguityTarget().getFiducialId());
      SmartDashboard.putNumber("Lowest AprilTag Ambiguity Ambiguity", aprilTags.getLowestAmbiguityTarget().getPoseAmbiguity());

    }

    aprilTags.unFreeze();
```
All problems can be mitigated.

2023-02-25 14:41 UTC, tywilly approved these changes

2023-02-25 14:42 UTC, merged